### ISSUE TITLE
Find better way to organize config file

### ISSUE THREAD

**Issue by evanthegrayt** [evanthegrayt/standup_md#44]
Because we let the user set `editor` via the config file, but the `StandupMP` class doesn't use editor and loads the config file. 

We should probably add a `cli` sub-section to the YAML. Something like:
```yaml
current_header: Today

cli:
   editor: vim
```
